### ISSUE TITLE
SW-SQL_Server_Products.rdl for 2012

### ISSUE THREAD

**Issue by MSIH** [JhonnyTerminus/SCCM#1]
The SSRS report seems to be in SQL 2016 format and I am getting an error when trying to upload or open

**Comment by JhonnyTerminus** [comment]
What reporting server version are you using?

**Comment by JhonnyTerminus** [comment]
You can edit the file and modify the report definition to match your reporting server version. Then you just need to edit out the unsupported elements and you are good to go.

**Comment by JhonnyTerminus** [comment]
https://stackoverflow.com/questions/38902037/ssrs-report-definition-is-newer-than-server/
